dist: trusty
sudo: required

language: c

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo add-apt-repository ppa:dqlite-maintainers/master -y
  - sudo apt-get update -q
  - sudo apt-get install libsqlite3-dev libuv1-dev libco-dev -y

script:
  - autoreconf -i
  - ./configure --enable-debug "${AC_FLAGS}"
  - make
  - make ./dqlite-test
  - ./dqlite-test

compiler:
  - gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - lcov
      env:
         - MATRIX_EVAL="CC=gcc-8"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - lcov
            - zlib1g-dev
      env:
         - MATRIX_EVAL="CC=gcc-8 AC_FLAGS=--enable-experimental"

after_success:
  - bash <(curl -s https://codecov.io/bash) -g "./test*"
